export type Project = {
  id: string;
  title: string;
  tagline: string;
  desc: string;
  details: string;
  tags: string[];
  github: string;
  demo?: string;
  cover: string;
  year: string;
  status: string;
};

export const PROJECTS: Project[] = [
  {
    id: "jobo",
    title: "JoBo (Journalising Book)",
    tagline: "Written in these pages are the stories that you have penned down!",
    desc: "Uses OCR to pull text from photos of journals and notebooks — turning messy handwriting into searchable digital entries. A bridge between the analogue and digital self.",
    details: "Built with OpenCV for image preprocessing and Tesseract OCR for text extraction. Dramatically improves accuracy on real-world handwriting, with entries stored securely and made fully searchable.",
    tags: ["Python", "OpenCV", "Tesseract OCR", "NumPy", "Pandas"],
    github: "https://github.com/kalpanajoycedovari/JoBo-OCR-digital-journal",
    cover: "/projects/jobo-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "solites-corner",
    title: "Solite's Corner",
    tagline: "A cozy safe space on the internet, for you....& just YOU!",
    desc: "A personal website with a full email login system and Firebase-backed storage — built with care, hosted on GitHub Pages, and engineered to feel like home the moment you land on it.",
    details: "Implements Firebase Authentication for secure email login and Firebase Storage for user data. Hosted on GitHub Pages — demonstrating a full-stack mindset even in a static site environment.",
    tags: ["Firebase", "GitHub Pages", "Email Auth", "JavaScript"],
    github: "https://github.com/kalpanajoycedovari/My-Website",
    demo: "https://kalpanajoycedovari.github.io/My-Website/",
    cover: "/projects/solite-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "speech-recognition",
    title: "Speech Recognition Pipeline",
    tagline: "Teaching machines to listen.",
    desc: "A lightweight speech recognition pipeline built around Facebook's Wav2Vec 2.0 model. Takes raw audio input and transcribes it into text — clean, accurate speech-to-text that actually works.",
    details: "Built using PyTorch and Wav2Vec 2.0 for feature extraction and transcription, with NumPy handling audio signal processing. Designed as a modular pipeline that plugs into larger AI systems.",
    tags: ["Wav2Vec", "PyTorch", "NumPy", "Speech Processing"],
    github: "https://github.com/kalpanajoycedovari/Speech-Recognition-Mini-Pipeline",
    cover: "/projects/speech-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "ai-resume-analyzer",
    title: "AI Resume Analyzer",
    tagline: "Your resume, but smarter.",
    desc: "NLP-powered tool that reads your resume the way a recruiter does — scanning for keywords, structure, and relevance. Gives actionable feedback instead of leaving you guessing.",
    details: "Uses spaCy for named entity recognition and keyword extraction, with a scoring system that compares resume content against job description patterns. Deployed live on Render.",
    tags: ["NLP", "Python", "Machine Learning", "spaCy", "FastAPI"],
    github: "https://github.com/kalpanajoycedovari/AI-resume-screener",
    demo: "https://ai-resume-screener-x5c1.onrender.com/",
    cover: "/projects/resume-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "scamcheck-agent",
    title: "ScamCheck Agent",
    tagline: "Because 'it looked legit' is not a fraud prevention strategy.",
    desc: "An intelligent scam detection agent built on Cloudflare's edge infrastructure. Paste a URL and it runs page analysis, Reddit scanning, and Llama 3.1 AI verdict in parallel — returning a trust score with animated breakdown bars, full conversation memory, and follow-up question support.",
    details: "Built with Cloudflare Workers, Durable Objects for session memory, Workers AI (Llama 3.1 8B), and WebSockets for live status updates. The agent remembers every URL you've checked, caches results, and lets you compare two sites side by side. Evolved from ScamScan — the same signal detection logic, now with memory, conversation, and real reasoning.",
    tags: ["Cloudflare Workers", "Durable Objects", "Llama 3.1", "Workers AI", "TypeScript", "WebSockets", "Reddit API"],
    github: "https://github.com/kalpanajoycedovari/cf_ai_scamcheck_agent",
    demo: "https://cf-ai-scamcheck-agent.dovarikalpanajoyce.workers.dev/",
    cover: "/projects/scamcheck-cover.jpg",
    year: "2025",
    status: "Live",
  },
  {
    id: "scamscan",
    title: "ScamScan",
    tagline: "Because not everything with 5 stars deserves your money.",
    desc: "An end-to-end data pipeline that scrapes 6,000+ Reddit posts, detects scam signals using NLP and a custom red flag keyword engine, and scores each entry on a 0–100 trust scale.",
    details: "99.6% of Reddit posts mentioning course keywords were flagged as likely scams. Built with TextBlob sentiment analysis, SQLite with 3 normalised tables, and an interactive Streamlit dashboard.",
    tags: ["Python", "NLP", "TextBlob", "SQLite", "Streamlit", "Plotly"],
    github: "https://github.com/kalpanajoycedovari/scamscan",
    cover: "/projects/scamscan-cover.jpg",
    year: "2025",
    status: "Completed",
  },
  {
    id: "commit-roaster",
    title: "Commit Roaster",
    tagline: "Your code is fine. Your commit messages? Not so much.",
    desc: "A Streamlit app that reads your Git commit history and roasts it — mercilessly, specifically, and with love. Because 'fixed stuff' is not a commit message.",
    details: "Built with Streamlit and the Claude API. Lightweight, ruthlessly funny, and genuinely useful for developers who need a mirror held up to their version control habits.",
    tags: ["Python", "Streamlit", "Claude API"],
    github: "https://github.com/kalpanajoycedovari/commit-roaster",
    demo: "https://commit-roaster.streamlit.app/",
    cover: "/projects/roaster-cover.jpg",
    year: "2025",
    status: "Live",
  },
  {
    id: "uk-job-market",
    title: "UK Job Market Dashboard",
    tagline: "1.6 million job postings walked so this dashboard could run.",
    desc: "Interactive Tableau dashboard analysing the UK job market across top hiring companies, work type distribution, and experience level requirements.",
    details: "Built on a 1.6M row Kaggle dataset filtered to UK postings. Key insight: mid-range experience (1–12 years) dominates demand. Published live on Tableau Public.",
    tags: ["Tableau", "Data Analytics", "SQL", "Data Visualisation"],
    github: "https://github.com/kalpanajoycedovari/uk-job-market-dashboard",
    demo: "https://public.tableau.com/app/profile/kalpana.joyce.dovari/viz/UKJobMarketDashboard/UKJobMarketDashboard?publish=yes",
    cover: "/projects/tableau-cover.jpg",
    year: "2025",
    status: "Completed",
  },
  
  {
    id: "zig-playground",
    title: "Zig Playground",
    tagline: "Learning at 5am like a nerd. No regrets.",
    desc: "A personal sandbox for Zig — a systems programming language I picked up out of pure curiosity. The commit messages alone tell the story.",
    details: "Built with Zig v0.15.2, covering basic syntax, memory management, and std.debug.print output. Small repo, big curiosity — proof that the best engineers never stop exploring.",
    tags: ["Zig", "Systems Programming"],
    github: "https://github.com/kalpanajoycedovari/zig-playground",
    cover: "/projects/zig-cover.jpg",
    year: "2025",
    status: "In Progress",
  },   
  {
  id: "komiso",
  title: "Komiso",
  tagline: "Set it, forget it — let the agents do the hustle.",
  desc: "Multi-agent affiliate automation system built in N8N that autonomously scouts affiliate programs, generates AI-written content, tracks performance metrics, and delivers weekly digest reports straight to Gmail.",
  details: "Built on a fully free stack using Groq LLaMA 3.3 for AI content generation, SerpAPI for scouting affiliate programs, and Google Sheets for performance tracking. Four chained agents handle the full pipeline end-to-end — Scout, Content, Tracker, and Report — running locally via N8N self-hosted.",
  tags: ["N8N", "Groq LLaMA 3.3", "SerpAPI", "Google Sheets"],
  github: "",
  cover: "/projects/komiso-cover.jpg",
  year: "2025",
  status: "Completed",
},
{
  id: "solene",
  title: "SOLÈNE",
  tagline: "This is just a mock-up, soon to be before the world",
  desc: "A luxury fashion editorial website built as a complete brand experience — shop, about, and designer submission pages unified under an ivory and gold visual identity.",
  details: "Built with vanilla HTML, CSS, and JavaScript with a Three.js geometric hero animation. Typography-led design using Cormorant Garamond and Raleway, hosted on GitHub Pages. Every page was crafted to feel like flipping through a high-fashion magazine.",
  tags: ["Three.js", "HTML/CSS", "JavaScript", "GitHub Pages"],
  github: "https://github.com/kalpanajoycedovari/solene-fashion",
  demo: "https://kalpanajoycedovari.github.io/solene-fashion/",
  cover: "/projects/solene-cover.jpg",
  year: "2026",
  status: "Completed",
}, 

];