export type Project = {
  id: string;
  title: string;
  tagline: string;
  desc: string;
  details: string;
  tags: string[];
  github: string;
  demo?: string;
  cover: string;
  year: string;
  status: string;
  collab?: { name: string; url: string };
};

export const PROJECTS: Project[] = [
  {
    id: "uk-job-market-pipeline",
    title: "UK Job Market Data Pipeline",
    tagline: "Real Azure. Real restrictions. Real pipeline anyway.",
    desc: "An end-to-end Azure data engineering pipeline that ingests, transforms, and visualises live UK job market data from three sources — Reed API, Adzuna API, and a Kaggle CSV — fully automated via GitHub Actions.",
    details: "Architected a star schema in ADLS Gen2, transformed data with Databricks Serverless (pandas over PySpark — the right call for 648 rows), queried via Synapse Analytics external tables, and visualised in a 5-page Power BI dashboard. Hit real Azure policy restrictions along the way: VM quota blocks, Azure Functions deprecation, and tenant-level storage denials — and solved each one with a defensible alternative. Total cloud spend: £1.81.",
    tags: ["Azure Data Lake Gen2", "Azure Databricks", "Azure Synapse Analytics", "Azure Data Factory", "Python", "Pandas", "Power BI", "GitHub Actions"],
    github: "https://github.com/kalpanajoycedovari/uk-job-market-pipeline",
    cover: "/projects/pipeline-cover.jpg",
    year: "2025",
    status: "Live",
  },
  {
    id: "tiktok-retention",
    title: "TikTok Retention Dashboard",
    tagline: "Acquiring a user is the easy part. Keeping them is where it gets interesting.",
    desc: "End-to-end analytics project analysing user retention, churn behaviour, and feature impact across a synthetic TikTok EMEA user base of 50,000 users spanning January to December 2024.",
    details: "User segments are modelled with weighted sampling (Casual 40%, Lurker 25%, Creator 20%, Power User 15%), churn timing via geometric distribution, and session counts via Poisson. Features a cohort retention heatmap, Kaplan-Meier-style survival curves per segment, logistic regression churn predictor with ROC curve, and a Streamlit dashboard with KPI cards, feature impact analysis, and sidebar filters.",
    tags: ["Python", "Streamlit", "Plotly", "Matplotlib", "Seaborn", "scikit-learn", "Pandas", "NumPy"],
    github: "https://github.com/kalpanajoycedovari/tiktok-retention-dashboard",
    demo: "https://tiktok-retention-dashboard.streamlit.app/",
    cover: "/projects/tiktok-retention-cover.jpg",
    year: "2026",
    status: "Live",
  },
  {
    id: "tiktok-ab-testing",
    title: "TikTok A/B Testing Suite",
    tagline: "Because 'ship it' should be a data-driven decision.",
    desc: "Simulates a real-world A/B experimentation suite across 4 concurrent TikTok product tests — with rigorous statistical analysis and an executive-grade Streamlit dashboard.",
    details: "Covers Welch's T-Test for continuous metrics, Chi-Square for conversion rates, Cohen's d for effect sizes, and power analysis for sample sizing. The Streamlit dashboard is designed to read like an internal TikTok product review doc — black header, gold accents, Playfair Display, and green/red verdict cards for instant decision clarity.",
    tags: ["Python", "Streamlit", "SciPy", "Pandas", "NumPy", "Plotly"],
    github: "https://github.com/kalpanajoycedovari/tiktok-ab-testing-analysis",
    demo: "https://tiktok-ab-testing-analysis.streamlit.app/",
    cover: "/projects/tiktok-ab-cover.jpg",
    year: "2026",
    status: "Live",
  },
  {
    id: "jobo",
    title: "JoBo (Journalising Book)",
    tagline: "Written in these pages are the stories that you have penned down!",
    desc: "Uses OCR to pull text from photos of journals and notebooks — turning messy handwriting into searchable digital entries.",
    details: "Built with OpenCV for image preprocessing and Tesseract OCR for text extraction. Dramatically improves accuracy on real-world handwriting, with entries stored securely and made fully searchable.",
    tags: ["Python", "OpenCV", "Tesseract OCR", "NumPy", "Pandas"],
    github: "https://github.com/kalpanajoycedovari/JoBo-OCR-digital-journal",
    cover: "/projects/jobo-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "solites-corner",
    title: "Solite's Corner",
    tagline: "A cozy safe space on the internet, for you....& just YOU!",
    desc: "A personal website with a full email login system and Firebase-backed storage — engineered to feel like home the moment you land on it.",
    details: "Implements Firebase Authentication for secure email login and Firebase Storage for user data. Hosted on GitHub Pages — demonstrating a full-stack mindset even in a static site environment.",
    tags: ["Firebase", "GitHub Pages", "Email Auth", "JavaScript"],
    github: "https://github.com/kalpanajoycedovari/My-Website",
    demo: "https://kalpanajoycedovari.github.io/My-Website/",
    cover: "/projects/solite-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "speech-recognition",
    title: "Speech Recognition Pipeline",
    tagline: "Teaching machines to listen.",
    desc: "A lightweight speech recognition pipeline built around Facebook's Wav2Vec 2.0 model. Raw audio in, accurate text out.",
    details: "Built using PyTorch and Wav2Vec 2.0 for feature extraction and transcription, with NumPy handling audio signal processing. Designed as a modular pipeline that plugs into larger AI systems.",
    tags: ["Wav2Vec", "PyTorch", "NumPy", "Speech Processing"],
    github: "https://github.com/kalpanajoycedovari/Speech-Recognition-Mini-Pipeline",
    cover: "/projects/speech-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "ai-resume-analyzer",
    title: "AI Resume Analyzer",
    tagline: "Your resume, but smarter.",
    desc: "NLP-powered tool that reads your resume the way a recruiter does — scanning for keywords, structure, and relevance.",
    details: "Uses spaCy for named entity recognition and keyword extraction, with a scoring system that compares resume content against job description patterns. Deployed live on Render.",
    tags: ["NLP", "Python", "Machine Learning", "spaCy", "FastAPI"],
    github: "https://github.com/kalpanajoycedovari/AI-resume-screener",
    demo: "https://ai-resume-screener-x5c1.onrender.com/",
    cover: "/projects/resume-cover.jpg",
    year: "2024",
    status: "Completed",
  },
  {
    id: "scamcheck-agent",
    title: "ScamCheck Agent",
    tagline: "Because 'it looked legit' is not a fraud prevention strategy.",
    desc: "Edge-hosted scam detection agent. Paste a URL — it runs page analysis, Reddit scanning, and AI verdict in parallel with live updates.",
    details: "Built with Cloudflare Workers, Durable Objects for session memory, Workers AI (Llama 3.1 8B), and WebSockets for live status updates. The agent remembers every URL you've checked, caches results, and lets you compare two sites side by side. Evolved from ScamScan — the same signal detection logic, now with memory, conversation, and real reasoning.",
    tags: ["Cloudflare Workers", "Durable Objects", "Llama 3.1", "Workers AI", "TypeScript", "WebSockets", "Reddit API"],
    github: "https://github.com/kalpanajoycedovari/cf_ai_scamcheck_agent",
    demo: "https://cf-ai-scamcheck-agent.dovarikalpanajoyce.workers.dev/",
    cover: "/projects/scamcheck-cover.jpg",
    year: "2025",
    status: "Live",
  },
  {
    id: "scamscan",
    title: "ScamScan",
    tagline: "Because not everything with 5 stars deserves your money.",
    desc: "Data pipeline that scrapes 6,000+ Reddit posts, detects scam signals using NLP, and scores each entry on a 0–100 trust scale.",
    details: "99.6% of Reddit posts mentioning course keywords were flagged as likely scams. Built with TextBlob sentiment analysis, SQLite with 3 normalised tables, and an interactive Streamlit dashboard.",
    tags: ["Python", "NLP", "TextBlob", "SQLite", "Streamlit", "Plotly"],
    github: "https://github.com/kalpanajoycedovari/scamscan",
    cover: "/projects/scamscan-cover.jpg",
    year: "2025",
    status: "Completed",
  },
  {
    id: "commit-roaster",
    title: "Commit Roaster",
    tagline: "Your code is fine. Your commit messages? Not so much.",
    desc: "Reads your Git commit history and roasts it — mercilessly, specifically, and with love. Because 'fixed stuff' is not a commit message.",
    details: "Built with Streamlit and the Claude API. Lightweight, ruthlessly funny, and genuinely useful for developers who need a mirror held up to their version control habits.",
    tags: ["Python", "Streamlit", "Claude API"],
    github: "https://github.com/kalpanajoycedovari/commit-roaster",
    demo: "https://commit-roaster.streamlit.app/",
    cover: "/projects/roaster-cover.jpg",
    year: "2025",
    status: "Live",
  },
  {
    id: "uk-job-market",
    title: "UK Job Market Dashboard",
    tagline: "1.6 million job postings walked so this dashboard could run.",
    desc: "Interactive Tableau dashboard analysing the UK job market across top hiring companies, work type, and experience level.",
    details: "Built on a 1.6M row Kaggle dataset filtered to UK postings. Key insight: mid-range experience (1–12 years) dominates demand. Published live on Tableau Public.",
    tags: ["Tableau", "Data Analytics", "SQL", "Data Visualisation"],
    github: "https://github.com/kalpanajoycedovari/uk-job-market-dashboard",
    demo: "https://public.tableau.com/app/profile/kalpana.joyce.dovari/viz/UKJobMarketDashboard/UKJobMarketDashboard?publish=yes",
    cover: "/projects/tableau-cover.jpg",
    year: "2025",
    status: "Completed",
  },
  {
    id: "zig-playground",
    title: "Zig Playground",
    tagline: "Learning at 5am like a nerd. No regrets.",
    desc: "A personal sandbox for Zig — a systems language picked up out of pure curiosity. The commit messages tell the whole story.",
    details: "Built with Zig v0.15.2, covering basic syntax, memory management, and std.debug.print output. Small repo, big curiosity — proof that the best engineers never stop exploring.",
    tags: ["Zig", "Systems Programming"],
    github: "https://github.com/kalpanajoycedovari/zig-playground",
    cover: "/projects/zig-cover.jpg",
    year: "2025",
    status: "In Progress",
  },
  {
    id: "komiso",
    title: "Komiso",
    tagline: "Set it, forget it — let the agents do the hustle.",
    desc: "Multi-agent affiliate automation in N8N — scouts programs, generates content, tracks metrics, and emails weekly digest reports.",
    details: "Built on a fully free stack using Groq LLaMA 3.3 for AI content generation, SerpAPI for scouting affiliate programs, and Google Sheets for performance tracking. Four chained agents handle the full pipeline end-to-end — Scout, Content, Tracker, and Report — running locally via N8N self-hosted.",
    tags: ["N8N", "Groq LLaMA 3.3", "SerpAPI", "Google Sheets"],
    github: "",
    cover: "/projects/komiso-cover.jpg",
    year: "2025",
    status: "Completed",
  },
  {
    id: "solene",
    title: "SOLÈNE",
    tagline: "This is just a mock-up, soon to be before the world",
    desc: "A luxury fashion editorial website — shop, about, and designer submission pages unified under an ivory and gold visual identity.",
    details: "Built with vanilla HTML, CSS, and JavaScript with a Three.js geometric hero animation. Typography-led design using Cormorant Garamond and Raleway, hosted on GitHub Pages. Every page was crafted to feel like flipping through a high-fashion magazine.",
    tags: ["Three.js", "HTML/CSS", "JavaScript", "GitHub Pages"],
    github: "https://github.com/kalpanajoycedovari/solene-fashion",
    demo: "https://kalpanajoycedovari.github.io/solene-fashion/",
    cover: "/projects/solene-cover.jpg",
    year: "2026",
    status: "Completed",
  },
  {
    id: "mi-armoire",
    title: "Mi Armoire",
    tagline: "Your wardrobe, curated by AI — dressed for the moment.",
    desc: "AI styling agent that builds complete outfits with FLUX-generated visuals. Pick your occasion, choose how many looks — done.",
    details: "Built with LangGraph for a four-node agentic pipeline, Groq LLaMA 3.3 70B for styling intelligence, and FLUX.1-schnell via HuggingFace Inference Router for image generation. Streamlit UI with a luxury SOLÈNE-inspired aesthetic — Cormorant Garamond, cream and gold palette, SVG geometric hero. Deployed live on Streamlit Cloud.",
    tags: ["LangGraph", "Groq", "FLUX.1-schnell", "HuggingFace", "Streamlit", "Python"],
    github: "https://github.com/kalpanajoycedovari/miarmoire",
    demo: "https://miarmoire.streamlit.app/",
    cover: "/projects/miarmoire-cover.jpg",
    year: "2026",
    status: "Live",
  },
  {
    id: "nexus-edu",
    title: "NexusEdu",
    tagline: "Learning that adapts to you, not the other way around.",
    desc: "Hackathon-built AI tutoring system with multi-agent workflows that adapt learning paths by grade level and style.",
    details: "Built as part of a group hackathon for our MSc course module. NexusEdu uses n8n multi-agent workflows to generate personalised learning paths, with OpenRouter routing to Llama for LLM-powered content generation tailored by grade level. Supabase handles persistent student data and session memory. Self-hosted, no public deployment.",
    tags: ["n8n", "OpenRouter", "Llama", "Supabase"],
    github: "",
    cover: "/projects/nexusedu-cover.jpg",
    year: "2026",
    status: "Completed",
    collab: {
      name: "Ramya Sri Muthuluri",
      url: "https://ramya-portfolio-ten.vercel.app/",
    },
  },
];